variables:
    GIT_STRATEGY: clone

stages:
  - build
  - deploy

build html pages:
  stage: build
  tags:
    - web
  script:
    - mkdocs --verbose build
  artifacts:
    paths:
      - public

deploy html to nginx directory:
  stage: deploy
  tags:
    - web
  only:
    - master
    - merge_request
  script:
    - rsync -avr --progress --delete public/ /var/lib/www/docs.hpc.sjtu.edu.cn/
