image: python:3.7

variables:
    GIT_STRATEGY: clone

stages:
  - build
  - deploy

build html pages:
  stage: build
  tags:
    - web
  before_script:
    - mkdir -p .build_cache
    - pip install --upgrade --cache-dir=.build_cache -r requirements.txt
  script:
    - mkdocs --verbose build
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .build_cache

deploy html to nginx directory:
  stage: deploy
  tags:
    - web
  only:
    - master
    - merge_request
  before_script:
    - sudo apt-get install rsync
  script:
    - rsync -avr --progress --delete public/ /var/lib/www/docs.hpc.sjtu.edu.cn/
